//! Protocol-mode exec proxy loops for byte-preserving stdio forwarding.
//!
//! Unlike interactive attached sessions, protocol mode must behave as a raw
//! stdio bridge. That means no terminal resize handling, no local echo, and no
//! host-generated bytes on stdout.
//!
//! ## Stdout Purity Contract
//!
//! The protocol proxy must never write bytes to host stdout that did not
//! originate from container stdout or console output. This means:
//!
//! - No banners, progress indicators, or status messages
//! - No diagnostic output or error messages (these go to stderr)
//! - No echoed stdin bytes (explicitly suppressed via `LogOutput::StdIn` routing)
//! - No framing, escaping, or encoding of the byte stream
//!
//! This contract is enforced by construction: `run_protocol_session_with_io_async`
//! accepts injected host-IO handles and only writes to `host_stdout` in
//! `handle_log_output_chunk` for `LogOutput::StdOut` and `LogOutput::Console`
//! messages from the container. All other code paths route to stderr or return
//! errors without touching stdout.

use std::io;
use std::pin::Pin;
use std::time::Duration;

use bollard::container::LogOutput;
use bollard::errors::Error as BollardError;
use futures_util::{Stream, StreamExt};
use tokio::io::{AsyncRead, AsyncWrite, AsyncWriteExt};
use tokio::task::JoinHandle;
use tokio::time::timeout;

use super::host_io::default_host_stdin;
use super::{ExecRequest, exec_failed};
use crate::error::PodbotError;

/// Host-side stdio handles used by the protocol byte proxy.
pub(super) struct ProtocolProxyIo<HostStdin, HostStdout, HostStderr> {
    stdin: HostStdin,
    stdout: HostStdout,
    stderr: HostStderr,
}

/// Allow a short grace period for EOF- and flush-driven completion paths to
/// finish before treating stdin forwarding as stalled. `50ms` matches typical
/// local pipe and socket flush timings in this code path without adding a
/// noticeable shutdown delay; if future benchmarks or transport changes show
/// different behaviour, adjust `STDIN_SETTLE_TIMEOUT` and extend the proxy
/// tests that exercise EOF and non-EOF stdin shutdown cases.
const STDIN_SETTLE_TIMEOUT: Duration = Duration::from_millis(50);

/// Maximum bytes buffered between host stdin reads and container input writes.
/// This bounds memory consumption per read cycle and provides backpressure by
/// limiting how many bytes can be in flight. A 64 KiB buffer aligns with common
/// protocol message sizes and typical OS pipe buffer defaults, keeping latency
/// low while preventing unbounded accumulation during high-throughput scenarios.
const STDIN_BUFFER_CAPACITY: usize = 65_536;

#[derive(Debug, Clone, Copy, Default)]
pub(super) struct ProtocolSessionOptions {
    disable_stdin_forwarding: bool,
}

impl ProtocolSessionOptions {
    pub(super) const fn new() -> Self {
        Self {
            disable_stdin_forwarding: false,
        }
    }

    pub(super) const fn with_stdin_forwarding_disabled(mut self, disable: bool) -> Self {
        self.disable_stdin_forwarding = disable;
        self
    }
}

impl<HostStdin, HostStdout, HostStderr> ProtocolProxyIo<HostStdin, HostStdout, HostStderr> {
    /// Create a host-IO bundle for a protocol proxy session.
    pub(super) const fn new(
        host_stdin: HostStdin,
        host_stdout: HostStdout,
        host_stderr: HostStderr,
    ) -> Self {
        Self {
            stdin: host_stdin,
            stdout: host_stdout,
            stderr: host_stderr,
        }
    }
}

pub(super) async fn run_protocol_session_async_with_options(
    request: &ExecRequest,
    output: Pin<Box<dyn Stream<Item = Result<LogOutput, BollardError>> + Send>>,
    input: Pin<Box<dyn AsyncWrite + Send>>,
    options: ProtocolSessionOptions,
) -> Result<(), PodbotError> {
    let stdio = ProtocolProxyIo::new(
        protocol_host_stdin(options),
        tokio::io::stdout(),
        tokio::io::stderr(),
    );
    run_protocol_session_with_io_async(request, output, input, stdio).await
}

fn protocol_host_stdin(options: ProtocolSessionOptions) -> Pin<Box<dyn AsyncRead + Send>> {
    if options.disable_stdin_forwarding {
        Box::pin(tokio::io::empty())
    } else {
        default_host_stdin()
    }
}

/// Run a protocol exec session using caller-supplied host IO handles.
pub(super) async fn run_protocol_session_with_io_async<HostStdin, HostStdout, HostStderr>(
    request: &ExecRequest,
    mut output: Pin<Box<dyn Stream<Item = Result<LogOutput, BollardError>> + Send>>,
    input: Pin<Box<dyn AsyncWrite + Send>>,
    stdio: ProtocolProxyIo<HostStdin, HostStdout, HostStderr>,
) -> Result<(), PodbotError>
where
    HostStdin: AsyncRead + Send + Unpin + 'static,
    HostStdout: AsyncWrite + Send + Unpin,
    HostStderr: AsyncWrite + Send + Unpin,
{
    let ProtocolProxyIo {
        stdin: host_stdin,
        stdout: mut host_stdout,
        stderr: mut host_stderr,
    } = stdio;
    let stdin_task = spawn_stdin_forwarding_task(host_stdin, input);
    let output_result = run_output_loop_async(
        request.container_id(),
        &mut output,
        &mut host_stdout,
        &mut host_stderr,
    )
    .await;
    let stdin_result = settle_stdin_forwarding_task(request.container_id(), stdin_task).await;
    output_result?;
    stdin_result
}

fn spawn_stdin_forwarding_task<HostStdin>(
    host_stdin: HostStdin,
    input: Pin<Box<dyn AsyncWrite + Send>>,
) -> JoinHandle<io::Result<()>>
where
    HostStdin: AsyncRead + Send + Unpin + 'static,
{
    tokio::spawn(async move { forward_host_stdin_to_exec_async(host_stdin, input).await })
}

async fn settle_stdin_forwarding_task(
    container_id: &str,
    mut stdin_task: JoinHandle<io::Result<()>>,
) -> Result<(), PodbotError> {
    let Ok(join_result) = timeout(STDIN_SETTLE_TIMEOUT, &mut stdin_task).await else {
        // The container output path has already completed, so stdin can be
        // cancelled instead of waiting indefinitely on a live host reader. A
        // timeout here still indicates that stdin forwarding did not complete
        // cleanly before shutdown, so protocol mode must surface that failure
        // instead of reporting success with potentially truncated input.
        abort_stdin_forwarding_task(stdin_task);
        return Err(exec_failed(
            container_id,
            "stdin forwarding did not complete before protocol session shutdown",
        ));
    };

    classify_stdin_forwarding_task_result(container_id, join_result)
}

fn classify_stdin_forwarding_task_result(
    container_id: &str,
    join_result: Result<io::Result<()>, tokio::task::JoinError>,
) -> Result<(), PodbotError> {
    match join_result {
        Ok(Ok(())) => Ok(()),
        Ok(Err(error)) => Err(exec_failed(
            container_id,
            format!("failed forwarding stdin to exec input: {error}"),
        )),
        Err(error) if error.is_cancelled() => Ok(()),
        Err(error) => Err(exec_failed(
            container_id,
            format!("stdin forwarding task failed: {error}"),
        )),
    }
}

fn abort_stdin_forwarding_task(stdin_task: JoinHandle<io::Result<()>>) {
    if !stdin_task.is_finished() {
        stdin_task.abort();
        // Avoid awaiting the aborted task here because host stdin may be
        // blocked in a non-cancellable read. Dropping the handle mirrors the
        // attached-session shutdown path and keeps teardown bounded.
        drop(stdin_task);
    }
}

async fn forward_host_stdin_to_exec_async<HostStdin>(
    host_stdin: HostStdin,
    mut input: Pin<Box<dyn AsyncWrite + Send>>,
) -> io::Result<()>
where
    HostStdin: AsyncRead + Unpin,
{
    let mut buffered_stdin = tokio::io::BufReader::with_capacity(STDIN_BUFFER_CAPACITY, host_stdin);
    tokio::io::copy(&mut buffered_stdin, &mut input).await?;
    input.flush().await?;
    input.shutdown().await
}

async fn run_output_loop_async<HostStdout, HostStderr>(
    container_id: &str,
    output: &mut Pin<Box<dyn Stream<Item = Result<LogOutput, BollardError>> + Send>>,
    host_stdout: &mut HostStdout,
    host_stderr: &mut HostStderr,
) -> Result<(), PodbotError>
where
    HostStdout: AsyncWrite + Unpin,
    HostStderr: AsyncWrite + Unpin,
{
    while let Some(chunk_result) = output.next().await {
        let chunk = chunk_result
            .map_err(|error| exec_failed(container_id, format!("exec stream failed: {error}")))?;
        handle_log_output_chunk(container_id, chunk, host_stdout, host_stderr).await?;
    }

    Ok(())
}

async fn handle_log_output_chunk<HostStdout, HostStderr>(
    container_id: &str,
    chunk: LogOutput,
    host_stdout: &mut HostStdout,
    host_stderr: &mut HostStderr,
) -> Result<(), PodbotError>
where
    HostStdout: AsyncWrite + Unpin,
    HostStderr: AsyncWrite + Unpin,
{
    match chunk {
        LogOutput::StdOut { message } | LogOutput::Console { message } => {
            write_output_chunk(container_id, host_stdout, message.as_ref(), "stdout").await
        }
        LogOutput::StdErr { message } => {
            write_output_chunk(container_id, host_stderr, message.as_ref(), "stderr").await
        }
        LogOutput::StdIn { .. } => Ok(()),
    }
}

async fn write_output_chunk<Writer>(
    container_id: &str,
    writer: &mut Writer,
    bytes: &[u8],
    stream_name: &str,
) -> Result<(), PodbotError>
where
    Writer: AsyncWrite + Unpin,
{
    writer.write_all(bytes).await.map_err(|error| {
        exec_failed(
            container_id,
            format!("failed writing {stream_name} output: {error}"),
        )
    })?;
    writer.flush().await.map_err(|error| {
        exec_failed(
            container_id,
            format!("failed flushing {stream_name} output: {error}"),
        )
    })?;
    Ok(())
}
