//! Protocol-mode exec proxy loops for byte-preserving stdio forwarding.
//!
//! Unlike interactive attached sessions, protocol mode must behave as a raw
//! stdio bridge. That means no terminal resize handling, no local echo, and no
//! host-generated bytes on stdout.
//!
//! ## Stdout Purity Contract
//!
//! The protocol proxy must never write bytes to host stdout that did not
//! originate from container stdout or console output. This means:
//!
//! - No banners, progress indicators, or status messages
//! - No diagnostic output or error messages (these go to stderr)
//! - No echoed stdin bytes (explicitly suppressed via `LogOutput::StdIn` routing)
//! - No framing, escaping, or encoding of the byte stream
//!
//! This contract is enforced by construction: `run_protocol_session_with_io_async`
//! accepts injected host-IO handles and only writes to `host_stdout` in
//! `handle_log_output_chunk` for `LogOutput::StdOut` and `LogOutput::Console`
//! messages from the container. All other code paths route to stderr or return
//! errors without touching stdout.
//!
//! ## Concurrency Model
//!
//! `run_protocol_session_with_io_async` runs two concurrent paths:
//!
//! 1. **Stdin forwarding task** — spawned via `spawn_stdin_forwarding_task`,
//!    which takes ownership of the host-stdin reader and the container-input
//!    writer. The task runs on the Tokio thread pool and is represented by a
//!    `JoinHandle<io::Result<()>>`. Ownership of the handle is retained by the
//!    caller function for the lifetime of the session.
//!
//! 2. **Output loop** — driven directly on the caller task via
//!    `run_output_loop_async`. It polls the container output stream to
//!    completion before any stdin shutdown logic runs.
//!
//! ### Task coordination
//!
//! The output loop is awaited to completion first. Once it returns (success or
//! error), `settle_stdin_forwarding_task` awaits the stdin handle with a
//! [`STDIN_SETTLE_TIMEOUT`] deadline of 50 ms. This grace period covers the
//! common case where container EOF propagates to the forwarding task within
//! normal pipe-flush timings.
//!
//! ### Timeout and cancellation
//!
//! If the grace period expires, `abort_stdin_forwarding_task` calls
//! `JoinHandle::abort` and immediately drops the handle **without awaiting
//! it**. Awaiting after abort would block indefinitely if host stdin is stalled
//! in a non-cancellable kernel read; dropping the handle mirrors the
//! attached-session teardown path and keeps shutdown bounded.
//!
//! A `JoinError` carrying `is_cancelled()` is mapped to `Ok(())` because an
//! explicit abort is an intentional shutdown signal, not a failure.
//!
//! When `disable_stdin_forwarding` is set, the forwarding task reads from a
//! `HeldOpenStdin` duplex adapter that never yields bytes and never closes.
//! In that mode a timeout is expected and is silently treated as success.

use std::io;
use std::pin::Pin;
use std::task::{Context, Poll};

use bollard::container::LogOutput;
use bollard::errors::Error as BollardError;
use futures_util::Stream;
use tokio::io::{AsyncRead, AsyncWrite};

use super::ExecRequest;
use super::acp_frame::OutboundFrameAssembler;
use super::acp_policy::MethodDenylist;
use super::acp_runtime::{
    OutboundPolicyAdapter, SINK_CHANNEL_CAPACITY, WriteCmd, run_container_stdin_sink,
};
use super::helpers::spawn_stdin_forwarding_task;
use super::host_io::stdin_forwarding_disabled_for_tests;
use super::runtime_helpers::exec_failed;
use super::session::CapabilityPolicy;
use crate::error::PodbotError;

#[path = "protocol_output.rs"]
mod output_io;
#[path = "protocol_stdin.rs"]
mod stdin_io;

use self::output_io::{AdapterOutputIo, run_output_loop_async, run_output_loop_with_adapter};
use self::stdin_io::{
    forward_host_stdin_to_channel, forward_host_stdin_to_exec_async, settle_stdin_forwarding_task,
};
/// Host-side stdio handles used by the protocol byte proxy.
pub(super) struct ProtocolProxyIo<HostStdin, HostStdout, HostStderr> {
    /// Host stdin reader supplied to the forwarding task.
    stdin: HostStdin,
    /// Host stdout writer used for container stdout and console output.
    stdout: HostStdout,
    /// Host stderr writer used for container stderr and error diagnostics.
    stderr: HostStderr,
    /// Per-session configuration knobs applied to this proxy run.
    options: ProtocolSessionOptions,
}

/// Maximum bytes buffered between host stdin reads and container input writes.
/// This bounds memory consumption per read cycle and provides backpressure by
/// limiting how many bytes can be in flight. A 64 KiB buffer aligns with common
/// protocol message sizes and typical OS pipe buffer defaults, keeping latency
/// low while preventing unbounded accumulation during high-throughput scenarios.
pub(super) const STDIN_BUFFER_CAPACITY: usize = 65_536;

/// Per-session configuration knobs for protocol-mode exec proxy loops.
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq)]
pub(super) struct ProtocolSessionOptions {
    /// When `true`, host stdin is replaced by a held-open no-op reader so that
    /// the process's inherited stdin is never forwarded to the container.
    disable_stdin_forwarding: bool,
    /// When `true`, the first ACP `initialize` frame is rewritten to remove
    /// `terminal` and `fs` capabilities before being forwarded to the container.
    capability_policy: CapabilityPolicy,
}

impl ProtocolSessionOptions {
    /// Create default protocol-session options with production behaviour.
    pub(super) const fn new() -> Self {
        Self {
            disable_stdin_forwarding: false,
            capability_policy: CapabilityPolicy::Disabled,
        }
    }

    /// Disable or enable protocol stdin forwarding for this session.
    pub(super) const fn with_stdin_forwarding_disabled(mut self, disable: bool) -> Self {
        self.disable_stdin_forwarding = disable;
        self
    }

    /// Select the [`CapabilityPolicy`] that governs Agentic Control Protocol
    /// (ACP) capability masking and runtime denylist enforcement for this
    /// protocol session.
    pub(super) const fn with_capability_policy(mut self, policy: CapabilityPolicy) -> Self {
        self.capability_policy = policy;
        self
    }
}

/// An `AsyncRead` adapter that stays open indefinitely without producing
/// bytes, used to suppress inherited process stdin while the forwarding task
/// remains alive.
struct HeldOpenStdin {
    /// The read half of the in-memory duplex pipe; never yields bytes.
    reader: tokio::io::DuplexStream,
    /// Keeps the write half alive so `reader` never sees EOF.
    _writer_guard: tokio::io::DuplexStream,
}

impl tokio::io::AsyncRead for HeldOpenStdin {
    /// Delegates to the inner duplex reader, which blocks indefinitely without producing bytes.
    fn poll_read(
        mut self: Pin<&mut Self>,
        cx: &mut Context<'_>,
        buf: &mut tokio::io::ReadBuf<'_>,
    ) -> Poll<io::Result<()>> {
        Pin::new(&mut self.reader).poll_read(cx, buf)
    }
}

impl<HostStdin, HostStdout, HostStderr> ProtocolProxyIo<HostStdin, HostStdout, HostStderr> {
    /// Create a host-IO bundle for a protocol proxy session.
    pub(super) const fn new(
        host_stdin: HostStdin,
        host_stdout: HostStdout,
        host_stderr: HostStderr,
    ) -> Self {
        Self {
            stdin: host_stdin,
            stdout: host_stdout,
            stderr: host_stderr,
            options: ProtocolSessionOptions::new(),
        }
    }

    /// Attach session options to this host-IO bundle.
    pub(super) const fn with_options(mut self, options: ProtocolSessionOptions) -> Self {
        self.options = options;
        self
    }
}

/// Run a protocol exec session using real host stdio and the given session
/// options.
pub(super) async fn run_protocol_session_async_with_options(
    request: &ExecRequest,
    output: Pin<Box<dyn Stream<Item = Result<LogOutput, BollardError>> + Send>>,
    input: Pin<Box<dyn AsyncWrite + Send>>,
    options: ProtocolSessionOptions,
) -> Result<(), PodbotError> {
    let stdio = ProtocolProxyIo::new(
        protocol_host_stdin(options),
        tokio::io::stdout(),
        tokio::io::stderr(),
    )
    .with_options(options);
    run_protocol_session_with_io_async(request, output, input, stdio).await
}

/// Return the appropriate stdin reader for a protocol session. Yields a
/// held-open no-op reader when stdin forwarding is disabled.
fn protocol_host_stdin(options: ProtocolSessionOptions) -> Pin<Box<dyn AsyncRead + Send>> {
    if options.disable_stdin_forwarding || stdin_forwarding_disabled_for_tests() {
        let (writer_guard, reader) = tokio::io::duplex(1);
        Box::pin(HeldOpenStdin {
            reader,
            _writer_guard: writer_guard,
        })
    } else {
        Box::pin(tokio::io::stdin())
    }
}

/// Run a protocol exec session using caller-supplied host IO handles.
pub(super) async fn run_protocol_session_with_io_async<HostStdin, HostStdout, HostStderr>(
    request: &ExecRequest,
    output: Pin<Box<dyn Stream<Item = Result<LogOutput, BollardError>> + Send>>,
    input: Pin<Box<dyn AsyncWrite + Send>>,
    stdio: ProtocolProxyIo<HostStdin, HostStdout, HostStderr>,
) -> Result<(), PodbotError>
where
    HostStdin: AsyncRead + Send + Unpin + 'static,
    HostStdout: AsyncWrite + Send + Unpin,
    HostStderr: AsyncWrite + Send + Unpin,
{
    if stdio.options.capability_policy.allows_runtime_enforcement() {
        run_session_with_runtime_enforcement(request, output, input, stdio).await
    } else {
        run_session_without_runtime_enforcement(request, output, input, stdio).await
    }
}

async fn run_session_without_runtime_enforcement<HostStdin, HostStdout, HostStderr>(
    request: &ExecRequest,
    mut output: Pin<Box<dyn Stream<Item = Result<LogOutput, BollardError>> + Send>>,
    input: Pin<Box<dyn AsyncWrite + Send>>,
    stdio: ProtocolProxyIo<HostStdin, HostStdout, HostStderr>,
) -> Result<(), PodbotError>
where
    HostStdin: AsyncRead + Send + Unpin + 'static,
    HostStdout: AsyncWrite + Send + Unpin,
    HostStderr: AsyncWrite + Send + Unpin,
{
    let ProtocolProxyIo {
        stdin: host_stdin,
        stdout: mut host_stdout,
        stderr: mut host_stderr,
        options,
    } = stdio;
    let rewrite_acp_initialize = options.capability_policy.rewrites_initialize();
    let stdin_task =
        spawn_stdin_forwarding_task(host_stdin, input, move |stdin_reader, exec_input| {
            forward_host_stdin_to_exec_async(stdin_reader, exec_input, rewrite_acp_initialize)
        });
    let output_result = run_output_loop_async(
        request.container_id(),
        &mut output,
        &mut host_stdout,
        &mut host_stderr,
    )
    .await;
    let stdin_result =
        settle_stdin_forwarding_task(request.container_id(), stdin_task, options).await;
    output_result?;
    stdin_result
}

async fn run_session_with_runtime_enforcement<HostStdin, HostStdout, HostStderr>(
    request: &ExecRequest,
    mut output: Pin<Box<dyn Stream<Item = Result<LogOutput, BollardError>> + Send>>,
    input: Pin<Box<dyn AsyncWrite + Send>>,
    stdio: ProtocolProxyIo<HostStdin, HostStdout, HostStderr>,
) -> Result<(), PodbotError>
where
    HostStdin: AsyncRead + Send + Unpin + 'static,
    HostStdout: AsyncWrite + Send + Unpin,
    HostStderr: AsyncWrite + Send + Unpin,
{
    let ProtocolProxyIo {
        stdin: host_stdin,
        stdout: mut host_stdout,
        stderr: mut host_stderr,
        options,
    } = stdio;
    let rewrite_acp_initialize = options.capability_policy.rewrites_initialize();
    let container_id_owned = String::from(request.container_id());
    let (sink_tx, sink_rx) = tokio::sync::mpsc::channel::<WriteCmd>(SINK_CHANNEL_CAPACITY);
    let sink_task = tokio::spawn(run_container_stdin_sink(input, sink_rx));

    let stdin_sender = sink_tx.clone();
    let stdin_task = tokio::spawn(async move {
        forward_host_stdin_to_channel(host_stdin, stdin_sender, rewrite_acp_initialize).await
    });

    let assembler = OutboundFrameAssembler::new(MethodDenylist::default_families());
    let mut adapter = OutboundPolicyAdapter::new(assembler, sink_tx, container_id_owned);

    let mut adapter_io = AdapterOutputIo {
        adapter: &mut adapter,
        host_stdout: &mut host_stdout,
        host_stderr: &mut host_stderr,
    };
    let output_result =
        run_output_loop_with_adapter(request.container_id(), &mut output, &mut adapter_io).await;
    adapter.finish();
    drop(adapter);

    let stdin_result =
        settle_stdin_forwarding_task(request.container_id(), stdin_task, options).await;

    if let Err(error) = output_result {
        sink_task.abort();
        return Err(error);
    }
    if let Err(error) = stdin_result {
        sink_task.abort();
        return Err(error);
    }

    sink_task
        .await
        .map_err(|error| {
            exec_failed(
                request.container_id(),
                format!("container stdin sink task failed: {error}"),
            )
        })?
        .map_err(|error| {
            exec_failed(
                request.container_id(),
                format!("container stdin sink failed: {error}"),
            )
        })
}

#[cfg(test)]
#[path = "protocol_acp_tests.rs"]
mod acp_tests;
