//! Protocol-mode exec proxy loops for byte-preserving stdio forwarding.
//!
//! Unlike interactive attached sessions, protocol mode must behave as a raw
//! stdio bridge. That means no terminal resize handling, no local echo, and no
//! host-generated bytes on stdout.
//!
//! ## Stdout Purity Contract
//!
//! The protocol proxy must never write bytes to host stdout that did not
//! originate from container stdout or console output. This means:
//!
//! - No banners, progress indicators, or status messages
//! - No diagnostic output or error messages (these go to stderr)
//! - No echoed stdin bytes (explicitly suppressed via `LogOutput::StdIn` routing)
//! - No framing, escaping, or encoding of the byte stream
//!
//! This contract is enforced by construction: `run_protocol_session_with_io_async`
//! accepts injected host-IO handles and only writes to `host_stdout` in
//! `handle_log_output_chunk` for `LogOutput::StdOut` and `LogOutput::Console`
//! messages from the container. All other code paths route to stderr or return
//! errors without touching stdout.

use std::io;
use std::pin::Pin;
use std::task::{Context, Poll};
use std::time::Duration;

use bollard::container::LogOutput;
use bollard::errors::Error as BollardError;
use futures_util::{Stream, StreamExt};
use tokio::io::{AsyncRead, AsyncWrite, AsyncWriteExt};
use tokio::task::JoinHandle;
use tokio::time::timeout;

#[path = "acp_frame.rs"]
mod acp_frame;
#[path = "acp_helpers.rs"]
mod acp_helpers;
#[path = "acp_policy.rs"]
pub(super) mod acp_policy;
#[path = "acp_runtime.rs"]
mod acp_runtime;

use self::acp_frame::OutboundFrameAssembler;
use self::acp_policy::MethodDenylist;
use self::acp_runtime::{OutboundPolicyAdapter, SINK_CHANNEL_CAPACITY, WriteCmd, run_container_stdin_sink};
use super::helpers::spawn_stdin_forwarding_task;
use super::host_io::stdin_forwarding_disabled_for_tests;
use super::session::CapabilityPolicy;
use super::{ExecRequest, exec_failed};
use crate::error::PodbotError;

/// Host-side stdio handles used by the protocol byte proxy.
pub(super) struct ProtocolProxyIo<HostStdin, HostStdout, HostStderr> {
    stdin: HostStdin,
    stdout: HostStdout,
    stderr: HostStderr,
    options: ProtocolSessionOptions,
}

/// Allow a short grace period for EOF- and flush-driven completion paths to
/// finish before treating stdin forwarding as stalled. `50ms` matches typical
/// local pipe and socket flush timings in this code path without adding a
/// noticeable shutdown delay; if future benchmarks or transport changes show
/// different behaviour, adjust `STDIN_SETTLE_TIMEOUT` and extend the proxy
/// tests that exercise EOF and non-EOF stdin shutdown cases.
const STDIN_SETTLE_TIMEOUT: Duration = Duration::from_millis(50);

/// Maximum bytes buffered between host stdin reads and container input writes.
/// This bounds memory consumption per read cycle and provides backpressure by
/// limiting how many bytes can be in flight. A 64 KiB buffer aligns with common
/// protocol message sizes and typical OS pipe buffer defaults, keeping latency
/// low while preventing unbounded accumulation during high-throughput scenarios.
const STDIN_BUFFER_CAPACITY: usize = 65_536;

#[derive(Debug, Clone, Copy, Default, PartialEq, Eq)]
pub(super) struct ProtocolSessionOptions {
    disable_stdin_forwarding: bool,
    capability_policy: CapabilityPolicy,
}

impl ProtocolSessionOptions {
    pub(super) const fn new() -> Self {
        Self {
            disable_stdin_forwarding: false,
            capability_policy: CapabilityPolicy::Disabled,
        }
    }

    pub(super) const fn with_stdin_forwarding_disabled(mut self, disable: bool) -> Self {
        self.disable_stdin_forwarding = disable;
        self
    }

    /// Select the [`CapabilityPolicy`] that governs Agentic Control Protocol
    /// (ACP) capability masking and runtime denylist enforcement for this
    /// protocol session.
    pub(super) const fn with_capability_policy(mut self, policy: CapabilityPolicy) -> Self {
        self.capability_policy = policy;
        self
    }
}

struct HeldOpenStdin {
    // `tokio::io::duplex(1)` gives us the smallest possible in-memory pipe to
    // keep `reader` and `_writer_guard` alive without producing an immediate
    // EOF. No bytes are ever written through this seam; the 1-byte buffer just
    // satisfies Tokio's duplex constructor while avoiding wasted memory.
    reader: tokio::io::DuplexStream,
    _writer_guard: tokio::io::DuplexStream,
}

impl tokio::io::AsyncRead for HeldOpenStdin {
    fn poll_read(
        mut self: Pin<&mut Self>,
        cx: &mut Context<'_>,
        buf: &mut tokio::io::ReadBuf<'_>,
    ) -> Poll<io::Result<()>> {
        Pin::new(&mut self.reader).poll_read(cx, buf)
    }
}

impl<HostStdin, HostStdout, HostStderr> ProtocolProxyIo<HostStdin, HostStdout, HostStderr> {
    /// Create a host-IO bundle for a protocol proxy session.
    pub(super) const fn new(
        host_stdin: HostStdin,
        host_stdout: HostStdout,
        host_stderr: HostStderr,
    ) -> Self {
        Self {
            stdin: host_stdin,
            stdout: host_stdout,
            stderr: host_stderr,
            options: ProtocolSessionOptions::new(),
        }
    }

    pub(super) const fn with_options(mut self, options: ProtocolSessionOptions) -> Self {
        self.options = options;
        self
    }
}

pub(super) async fn run_protocol_session_async_with_options(
    request: &ExecRequest,
    output: Pin<Box<dyn Stream<Item = Result<LogOutput, BollardError>> + Send>>,
    input: Pin<Box<dyn AsyncWrite + Send>>,
    options: ProtocolSessionOptions,
) -> Result<(), PodbotError> {
    let stdio = ProtocolProxyIo::new(
        protocol_host_stdin(options),
        tokio::io::stdout(),
        tokio::io::stderr(),
    )
    .with_options(options);
    run_protocol_session_with_io_async(request, output, input, stdio).await
}

fn protocol_host_stdin(options: ProtocolSessionOptions) -> Pin<Box<dyn AsyncRead + Send>> {
    if options.disable_stdin_forwarding || stdin_forwarding_disabled_for_tests() {
        let (writer_guard, reader) = tokio::io::duplex(1);
        Box::pin(HeldOpenStdin {
            reader,
            _writer_guard: writer_guard,
        })
    } else {
        Box::pin(tokio::io::stdin())
    }
}

/// Run a protocol exec session using caller-supplied host IO handles.
pub(super) async fn run_protocol_session_with_io_async<HostStdin, HostStdout, HostStderr>(
    request: &ExecRequest,
    output: Pin<Box<dyn Stream<Item = Result<LogOutput, BollardError>> + Send>>,
    input: Pin<Box<dyn AsyncWrite + Send>>,
    stdio: ProtocolProxyIo<HostStdin, HostStdout, HostStderr>,
) -> Result<(), PodbotError>
where
    HostStdin: AsyncRead + Send + Unpin + 'static,
    HostStdout: AsyncWrite + Send + Unpin,
    HostStderr: AsyncWrite + Send + Unpin,
{
    if stdio.options.capability_policy.allows_runtime_enforcement() {
        run_session_with_runtime_enforcement(request, output, input, stdio).await
    } else {
        run_session_without_runtime_enforcement(request, output, input, stdio).await
    }
}

async fn run_session_without_runtime_enforcement<HostStdin, HostStdout, HostStderr>(
    request: &ExecRequest,
    mut output: Pin<Box<dyn Stream<Item = Result<LogOutput, BollardError>> + Send>>,
    input: Pin<Box<dyn AsyncWrite + Send>>,
    stdio: ProtocolProxyIo<HostStdin, HostStdout, HostStderr>,
) -> Result<(), PodbotError>
where
    HostStdin: AsyncRead + Send + Unpin + 'static,
    HostStdout: AsyncWrite + Send + Unpin,
    HostStderr: AsyncWrite + Send + Unpin,
{
    let ProtocolProxyIo {
        stdin: host_stdin,
        stdout: mut host_stdout,
        stderr: mut host_stderr,
        options,
    } = stdio;
    let rewrite_acp_initialize = options.capability_policy.rewrites_initialize();
    let stdin_task =
        spawn_stdin_forwarding_task(host_stdin, input, move |stdin_reader, exec_input| {
            forward_host_stdin_to_exec_async(stdin_reader, exec_input, rewrite_acp_initialize)
        });
    let output_result = run_output_loop_async(
        request.container_id(),
        &mut output,
        &mut host_stdout,
        &mut host_stderr,
    )
    .await;
    let stdin_result =
        settle_stdin_forwarding_task(request.container_id(), stdin_task, options).await;
    output_result?;
    stdin_result
}

async fn run_session_with_runtime_enforcement<HostStdin, HostStdout, HostStderr>(
    request: &ExecRequest,
    mut output: Pin<Box<dyn Stream<Item = Result<LogOutput, BollardError>> + Send>>,
    input: Pin<Box<dyn AsyncWrite + Send>>,
    stdio: ProtocolProxyIo<HostStdin, HostStdout, HostStderr>,
) -> Result<(), PodbotError>
where
    HostStdin: AsyncRead + Send + Unpin + 'static,
    HostStdout: AsyncWrite + Send + Unpin,
    HostStderr: AsyncWrite + Send + Unpin,
{
    let ProtocolProxyIo {
        stdin: host_stdin,
        stdout: mut host_stdout,
        stderr: mut host_stderr,
        options,
    } = stdio;
    let rewrite_acp_initialize = options.capability_policy.rewrites_initialize();
    let container_id_owned = String::from(request.container_id());
    let (sink_tx, sink_rx) = tokio::sync::mpsc::channel::<WriteCmd>(SINK_CHANNEL_CAPACITY);
    let sink_task = tokio::spawn(run_container_stdin_sink(input, sink_rx));

    let stdin_sender = sink_tx.clone();
    let stdin_task = tokio::spawn(async move {
        forward_host_stdin_to_channel(host_stdin, stdin_sender, rewrite_acp_initialize).await
    });

    let assembler = OutboundFrameAssembler::new(MethodDenylist::default_families());
    let mut adapter = OutboundPolicyAdapter::new(assembler, sink_tx, container_id_owned);

    let output_result = run_output_loop_with_adapter(
        request.container_id(),
        &mut output,
        &mut adapter,
        &mut host_stdout,
        &mut host_stderr,
    )
    .await;
    adapter.finish();
    drop(adapter);

    let stdin_result =
        settle_stdin_forwarding_task(request.container_id(), stdin_task, options).await;

    let sink_result = sink_task
        .await
        .map_err(|error| {
            exec_failed(
                request.container_id(),
                format!("container stdin sink task failed: {error}"),
            )
        })?
        .map_err(|error| {
            exec_failed(
                request.container_id(),
                format!("container stdin sink failed: {error}"),
            )
        });

    output_result?;
    stdin_result?;
    sink_result
}

async fn forward_host_stdin_to_channel<HostStdin>(
    host_stdin: HostStdin,
    sender: tokio::sync::mpsc::Sender<WriteCmd>,
    rewrite_acp_initialize: bool,
) -> io::Result<()>
where
    HostStdin: AsyncRead + Unpin,
{
    use tokio::io::AsyncReadExt;

    let mut buffered_stdin =
        tokio::io::BufReader::with_capacity(STDIN_BUFFER_CAPACITY, host_stdin);

    if rewrite_acp_initialize {
        let bytes = acp_helpers::read_and_mask_initial_acp_frame(&mut buffered_stdin).await?;
        if !bytes.is_empty() && sender.send(WriteCmd::Forward(bytes)).await.is_err() {
            return Ok(());
        }
    }

    let mut buf = vec![0u8; STDIN_BUFFER_CAPACITY];
    loop {
        let bytes_read = buffered_stdin.read(&mut buf).await?;
        if bytes_read == 0 {
            break;
        }
        let chunk = buf
            .get(..bytes_read)
            .map(<[u8]>::to_vec)
            .unwrap_or_default();
        if sender.send(WriteCmd::Forward(chunk)).await.is_err() {
            break;
        }
    }
    Ok(())
}

async fn run_output_loop_with_adapter<HostStdout, HostStderr>(
    container_id: &str,
    output: &mut Pin<Box<dyn Stream<Item = Result<LogOutput, BollardError>> + Send>>,
    adapter: &mut OutboundPolicyAdapter,
    host_stdout: &mut HostStdout,
    host_stderr: &mut HostStderr,
) -> Result<(), PodbotError>
where
    HostStdout: AsyncWrite + Unpin,
    HostStderr: AsyncWrite + Unpin,
{
    while let Some(chunk_result) = output.next().await {
        let chunk = chunk_result
            .map_err(|error| exec_failed(container_id, format!("exec stream failed: {error}")))?;
        match chunk {
            LogOutput::StdOut { message } | LogOutput::Console { message } => {
                adapter
                    .handle_chunk(message.as_ref(), host_stdout)
                    .await
                    .map_err(|error| {
                        exec_failed(container_id, format!("failed writing stdout output: {error}"))
                    })?;
            }
            LogOutput::StdErr { message } => {
                write_output_chunk(container_id, host_stderr, message.as_ref(), "stderr").await?;
            }
            LogOutput::StdIn { .. } => {}
        }
    }
    Ok(())
}

async fn settle_stdin_forwarding_task(
    container_id: &str,
    mut stdin_task: JoinHandle<io::Result<()>>,
    options: ProtocolSessionOptions,
) -> Result<(), PodbotError> {
    let Ok(join_result) = timeout(STDIN_SETTLE_TIMEOUT, &mut stdin_task).await else {
        // The container output path has already completed, so stdin can be
        // cancelled instead of waiting indefinitely on a live host reader. A
        // timeout here still indicates that stdin forwarding did not complete
        // cleanly before shutdown, so protocol mode must surface that failure
        // instead of reporting success with potentially truncated input.
        abort_stdin_forwarding_task(stdin_task);
        if options.disable_stdin_forwarding || stdin_forwarding_disabled_for_tests() {
            return Ok(());
        }
        return Err(exec_failed(
            container_id,
            "stdin forwarding did not complete before protocol session shutdown",
        ));
    };

    classify_stdin_forwarding_task_result(container_id, join_result)
}

fn classify_stdin_forwarding_task_result(
    container_id: &str,
    join_result: Result<io::Result<()>, tokio::task::JoinError>,
) -> Result<(), PodbotError> {
    match join_result {
        Ok(Ok(())) => Ok(()),
        Ok(Err(error)) => Err(exec_failed(
            container_id,
            format!("failed forwarding stdin to exec input: {error}"),
        )),
        Err(error) if error.is_cancelled() => Ok(()),
        Err(error) => Err(exec_failed(
            container_id,
            format!("stdin forwarding task failed: {error}"),
        )),
    }
}

fn abort_stdin_forwarding_task(stdin_task: JoinHandle<io::Result<()>>) {
    if !stdin_task.is_finished() {
        stdin_task.abort();
        // Avoid awaiting the aborted task here because host stdin may be
        // blocked in a non-cancellable read. Dropping the handle mirrors the
        // attached-session shutdown path and keeps teardown bounded.
        drop(stdin_task);
    }
}

async fn forward_host_stdin_to_exec_async<HostStdin>(
    host_stdin: HostStdin,
    mut input: Pin<Box<dyn AsyncWrite + Send>>,
    rewrite_acp_initialize: bool,
) -> io::Result<()>
where
    HostStdin: AsyncRead + Unpin,
{
    let mut buffered_stdin = tokio::io::BufReader::with_capacity(STDIN_BUFFER_CAPACITY, host_stdin);

    if rewrite_acp_initialize {
        acp_helpers::forward_initial_acp_frame_async(&mut buffered_stdin, &mut input).await?;
    }
    tokio::io::copy(&mut buffered_stdin, &mut input).await?;

    input.flush().await?;
    input.shutdown().await
}

#[cfg(test)]
#[path = "protocol_acp_tests.rs"]
mod acp_tests;

async fn run_output_loop_async<HostStdout, HostStderr>(
    container_id: &str,
    output: &mut Pin<Box<dyn Stream<Item = Result<LogOutput, BollardError>> + Send>>,
    host_stdout: &mut HostStdout,
    host_stderr: &mut HostStderr,
) -> Result<(), PodbotError>
where
    HostStdout: AsyncWrite + Unpin,
    HostStderr: AsyncWrite + Unpin,
{
    while let Some(chunk_result) = output.next().await {
        let chunk = chunk_result
            .map_err(|error| exec_failed(container_id, format!("exec stream failed: {error}")))?;
        handle_log_output_chunk(container_id, chunk, host_stdout, host_stderr).await?;
    }

    Ok(())
}

async fn handle_log_output_chunk<HostStdout, HostStderr>(
    container_id: &str,
    chunk: LogOutput,
    host_stdout: &mut HostStdout,
    host_stderr: &mut HostStderr,
) -> Result<(), PodbotError>
where
    HostStdout: AsyncWrite + Unpin,
    HostStderr: AsyncWrite + Unpin,
{
    match chunk {
        LogOutput::StdOut { message } | LogOutput::Console { message } => {
            write_output_chunk(container_id, host_stdout, message.as_ref(), "stdout").await
        }
        LogOutput::StdErr { message } => {
            write_output_chunk(container_id, host_stderr, message.as_ref(), "stderr").await
        }
        LogOutput::StdIn { .. } => Ok(()),
    }
}

async fn write_output_chunk<Writer>(
    container_id: &str,
    writer: &mut Writer,
    bytes: &[u8],
    stream_name: &str,
) -> Result<(), PodbotError>
where
    Writer: AsyncWrite + Unpin,
{
    writer.write_all(bytes).await.map_err(|error| {
        exec_failed(
            container_id,
            format!("failed writing {stream_name} output: {error}"),
        )
    })?;
    writer.flush().await.map_err(|error| {
        exec_failed(
            container_id,
            format!("failed flushing {stream_name} output: {error}"),
        )
    })?;
    Ok(())
}
